server:
  port: 8082
  servlet:
    context-path: /smart-manager

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: public
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/database}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver

security:
  jwt:
    issuer: smart-manager-api
    expires-in: 1800 # 30 minutes

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true

flyway:
  enabled: true
  locations: classpath:db/migration