services:
  db:
    image: postgres:15.3
    env_file:
      - .env
    ports:
      - 5432:5432
  backend:
    build:
      context: smart-manage-api
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8080:8080