services:
  db:
    image: postgres:15.3
    container_name: database
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - 5432:5432

  backend:
    build:
      context: smart-manage-api
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - 8080:8080

networks:
  app-network:
    driver: bridge